fix: simd-imgproc\src\Simd\SimdAmxBf16SynetMergedConvolution8iInput.cpp(464,13): warning C4062: enumerator 'SimdConvolutionActivationHardSigmoid' in switch of enum 'SimdConvolutionActivationType' is not handled simd-imgproc\src\Simd\SimdLib.h(153,1): message : see declaration of 'SimdConvolutionActivationType' simd-imgproc\src\Simd\SimdAmxBf16SynetMergedConvolution8iOutput.cpp(430,13): warning C4062: enumerator 'SimdConvolutionActivationHardSigmoid' in switch of enum 'SimdConvolutionActivationType' is not handled simd-imgproc\src\Simd\SimdLib.h(153,1): message : see declaration of 'SimdConvolutionActivationType'
simd-imgproc\src\Simd\SimdAvx2Gemm32f.cpp(889): warning C4703: potentially uninitialized local pointer variable 'kernelMM' used
simd-imgproc\src\Simd\SimdAvx2Gemm32f.cpp(889): warning C4703: potentially uninitialized local pointer variable 'kernelMT' used
simd-imgproc\src\Simd\SimdAvx2Gemm32f.cpp(889): warning C4703: potentially uninitialized local pointer variable 'kernelTM' used
simd-imgproc\src\Simd\SimdAvx2Gemm32f.cpp(889): warning C4703: potentially uninitialized local pointer variable 'kernelTT' used

simd-imgproc\src\Simd\SimdAvx512bwGemm32fNN.cpp(1454): warning C4703: potentially uninitialized local pointer variable 'kernelMM' used
simd-imgproc\src\Simd\SimdAvx512bwGemm32fNN.cpp(1454): warning C4703: potentially uninitialized local pointer variable 'kernelMT' used
simd-imgproc\src\Simd\SimdAvx512bwGemm32fNN.cpp(1454): warning C4703: potentially uninitialized local pointer variable 'kernelTM' used
simd-imgproc\src\Simd\SimdAvx512bwGemm32fNN.cpp(1454): warning C4703: potentially uninitialized local pointer variable 'kernelTT' used

libassert\include\libassert\expression-decomposition.hpp(59,9): error C2446: '!=': no conversion from 'A' to 'int64_t *'
1>        with
1>        [
1>            A=int
1>        ] (compiling source file simd-imgproc/src/Simd/SimdAvx512bwTexture.cpp)
libassert\include\libassert\expression-decomposition.hpp(59,9): message : Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or parenthesized function-style cast (compiling source file simd-imgproc/src/Simd/SimdAvx512bwTexture.cpp)

simd-imgproc\src\Simd\SimdAvx512bwWinograd3.cpp(325,37): warning C4800: Implicit conversion from 'size_t' to bool. Possible information loss
simd-imgproc\src\Simd\SimdAvx512bwWinograd3.cpp(325,37): message : consider using explicit cast or comparison to 0 to avoid this warning
simd-imgproc\src\Simd\SimdAvx512bwWinograd3.cpp : message : see declaration of 'size_t'

simd-imgproc\src\Simd\SimdBaseImageLoadPng.cpp(63,51): warning C4800: Implicit conversion from 'int' to bool. Possible information loss
simd-imgproc\src\Simd\SimdBaseImageLoadPng.cpp(63,51): message : consider using explicit cast or comparison to 0 to avoid this warning
simd-imgproc\src\Simd\SimdBaseImageLoadPng.cpp(72,51): warning C4800: Implicit conversion from 'int' to bool. Possible information loss
simd-imgproc\src\Simd\SimdBaseImageLoadPng.cpp(72,51): message : consider using explicit cast or comparison to 0 to avoid this warning
simd-imgproc\src\Simd\SimdBaseImageLoadPng.cpp(1107,36): warning C4800: Implicit conversion from 'int' to bool. Possible information loss
simd-imgproc\src\Simd\SimdBaseImageLoadPng.cpp(1107,36): message : consider using explicit cast or comparison to 0 to avoid this warning
simd-imgproc\src\Simd\SimdBaseImageLoadPng.cpp(1113,39): warning C4800: Implicit conversion from 'int' to bool. Possible information loss
simd-imgproc\src\Simd\SimdBaseImageLoadPng.cpp(1113,39): message : consider using explicit cast or comparison to 0 to avoid this warning
simd-imgproc\src\Simd\SimdBaseImageLoadPng.cpp(1122,43): warning C4800: Implicit conversion from 'int' to bool. Possible information loss
simd-imgproc\src\Simd\SimdBaseImageLoadPng.cpp(1122,43): message : consider using explicit cast or comparison to 0 to avoid this warning
simd-imgproc\src\Simd\SimdBaseImageLoadPng.cpp(1127,47): warning C4800: Implicit conversion from 'int' to bool. Possible information loss
simd-imgproc\src\Simd\SimdBaseImageLoadPng.cpp(1127,47): message : consider using explicit cast or comparison to 0 to avoid this warning

simd-imgproc\src\Simd\SimdSse41Gemm32fNN.cpp(666): warning C4703: potentially uninitialized local pointer variable 'kernelMM' used
simd-imgproc\src\Simd\SimdSse41Gemm32fNN.cpp(666): warning C4703: potentially uninitialized local pointer variable 'kernelMT' used
simd-imgproc\src\Simd\SimdSse41Gemm32fNN.cpp(666): warning C4703: potentially uninitialized local pointer variable 'kernelTM' used
simd-imgproc\src\Simd\SimdSse41Gemm32fNN.cpp(666): warning C4703: potentially uninitialized local pointer variable 'kernelTT' used